apiVersion: v1
kind: Service
metadata:
  name: qubeviz-server
  labels:
    app: qubeviz-server
    role: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: qubeviz-server
    role: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qubeviz-server
  labels:
    app: qubeviz-server
    role: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qubeviz-server
        role: web
    spec:
      containers:
      - name: qubeviz-server
        image: chiradeep/qubeviz-server
        imagePullPolicy: IfNotPresent
        name: qubeviz-server
      - name: kubectl
        image: kelseyhightower/kubectl:1.3.4
        args:
           - "proxy"
           - "--port=8080"
