apiVersion: v1
kind: Service
metadata:
  name: redis-viz
  labels:
    app: redis-viz
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-viz

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-viz
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-viz
    spec:
      containers:
      - name: master
        image: gcr.io/google_containers/redis:e2e  
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
